//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SopotnytskaOlhaPZ35
{
    using System;
    using System.Collections.Generic;
    
    public partial class member
    {
        public int id { get; set; }
        public string name { get; set; }
        public string director { get; set; }
        public string duration { get; set; }
        public string genre { get; set; }
        public string recommend { get; set; }
        public string comment { get; set; }
    }
}
